apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dspa-webhook-cert
  namespace: opendatahub
spec:
  commonName: dspa-webhook-cert
  isCA: false
  dnsNames:
  - ds-pipelines-webhook
  - ds-pipelines-webhook.opendatahub
  - ds-pipelines-webhook.opendatahub.svc
  - ds-pipelines-webhook.opendatahub.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: dspa-webhook-selfsigned-issuer
    group: cert-manager.io
  secretName: ds-pipelines-webhook-tls
