name: KinD DSPO/DSP Integration Tests - External Argo

on:
  workflow_dispatch:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - controllers/**
      - api/**
      - config/**
      - tests/**
      - .github/resources/**
      - .github/actions/**
      - '.github/workflows/kind-integration-byoargo.yml'
      - '.github/scripts/tests/tests.sh'
      - '.github/scripts/tests/build_kind_images.sh'
      - '.github/scripts/python_package_upload/**'
      - Makefile
    types:
      - opened
      - reopened
      - closed
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GIT_WORKSPACE: ${{ github.workspace }}
  DSP_SOURCE_BRANCH: ${{ github.base_ref || github.ref_name }}
  ARGO_SOURCE_BRANCH: ${{ github.base_ref || github.ref_name }}
  CONTAINER_CLI: podman
  KIND_IMAGE_TAG: kind-ci

jobs:
  dspo-byoargo-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set component source paths
        run: |
          echo "DSP_SOURCE_DIR=${RUNNER_TEMP}/dsp-src" >> "${GITHUB_ENV}"
          echo "ARGO_SOURCE_DIR=${RUNNER_TEMP}/argo-src" >> "${GITHUB_ENV}"

      - name: Checkout DSP source
        run: |
          git clone --depth 1 --branch "${DSP_SOURCE_BRANCH}" \
            https://github.com/red-hat-data-services/data-science-pipelines.git \
            "${DSP_SOURCE_DIR}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Setup and start KinD cluster
        uses: ./.github/actions/kind

      - name: Build and push DSP images
        working-directory: ${{ github.workspace }}
        run: |
          bash .github/scripts/build_dsp_images.sh
        env:
          REGISTRY_ADDRESS: ${{ env.REGISTRY_ADDRESS }}

      - name: Run test
        id: test
        working-directory: ${{ github.workspace }}/.github/scripts/tests
        run: |
          bash tests.sh --kind --deploy-external-argo --external-argo-version v3.7.3
        continue-on-error: true

      - name: Collect events and logs
        if: steps.test.outcome != 'success'
        working-directory: ${{ github.workspace }}/.github/scripts/tests
        run: |
          ./collect_logs.sh --dspa-ns test-dspa --dspo-ns opendatahub
          ./collect_logs.sh --dspa-ns dspa-ext --dspo-ns opendatahub
          ./collect_logs.sh --dspa-ns test-k8s-dspa --dspo-ns opendatahub
          ./collect_logs.sh --dspa-ns argo --dspo-ns opendatahub
          exit 1
