name: KinD DSPO/DSP Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - go.mod
      - go.sum
      - controllers/**
      - api/**
      - config/**
      - tests/**
      - .github/resources/**
      - .github/actions/**
      - '.github/workflows/kind-integration.yml'
      - '.github/scripts/tests/tests.sh'
      - '.github/scripts/python_package_upload/**'
      - Makefile
    types:
      - opened
      - reopened
      - closed
      - synchronize

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GIT_WORKSPACE: ${{ github.workspace }}

jobs:
  dspo-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: Setup and start KinD cluster
        uses: ./.github/actions/kind

      - name: Run test
        id: test
        working-directory: ${{ github.workspace }}/.github/scripts/tests
        env:
          IMAGES_APISERVER_OVERRIDE: quay.io/opendatahub/ds-pipelines-api-server@sha256:8bcd11b18662c4f900f425d6cdf2e27aafa1a6842c57c73cf71d6f14331afc6d
          IMAGES_LAUNCHER_OVERRIDE: quay.io/opendatahub/ds-pipelines-launcher@sha256:27a7502e54792985a170b88c065ceb0bf80c0088031a4f7c899574e9d15c6aa7
          IMAGES_DRIVER_OVERRIDE: quay.io/opendatahub/ds-pipelines-driver@sha256:3feb8920dbd299085cdf85ac878adfbb628d56f43517f3c32f0a843b348326c2
          IMAGES_PERSISTENCEAGENT_OVERRIDE: quay.io/opendatahub/ds-pipelines-persistenceagent@sha256:f9e5a989912190f31689fd42ed012e395c5409c45ef04a0ebb13a5f1b7b02f37
          IMAGES_SCHEDULEDWORKFLOW_OVERRIDE: quay.io/opendatahub/ds-pipelines-scheduledworkflow@sha256:7ec6ea47c00df60d2602487a518da39a1acd068fe397982d49db4936ce9ec973
        run: |
          bash tests.sh --kind
        continue-on-error: true

      - name: Collect events and logs
        if: steps.test.outcome != 'success'
        working-directory: ${{ github.workspace }}/.github/scripts/tests
        run: |
          ./collect_logs.sh --dspa-ns test-dspa --dspo-ns opendatahub
          ./collect_logs.sh --dspa-ns dspa-ext --dspo-ns opendatahub
          ./collect_logs.sh --dspa-ns test-k8s-dspa --dspo-ns opendatahub
          exit 1
